name: Manual Workflow

on:
  workflow_dispatch:  # Allows you to manually trigger the workflow from the GitHub UI

jobs:
    job_1:
        runs-on: ubuntu-latest

    steps: 
        - run: echo "The job triggered by ${{ github.event_name}}"
